//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.Model.Ui.Win.Common.Settings.Files {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Engine : global::System.Configuration.ApplicationSettingsBase {
        
        private static Engine defaultInstance = ((Engine)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Engine())));
        
        public static Engine Default {
            get {
                return defaultInstance;
            }
        }
    }
}
