//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model.Model.Ui.Win.Common.Settings.Files {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class GlobalSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSet defaultInstance = ((GlobalSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSet())));
        
        public static GlobalSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Notations {
            get {
                return ((string)(this["Notations"]));
            }
            set {
                this["Notations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpeningBookNotations {
            get {
                return ((string)(this["OpeningBookNotations"]));
            }
            set {
                this["OpeningBookNotations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClientScreenWidth {
            get {
                return ((int)(this["ClientScreenWidth"]));
            }
            set {
                this["ClientScreenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ClientScreenHeight {
            get {
                return ((int)(this["ClientScreenHeight"]));
            }
            set {
                this["ClientScreenHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int InfinityScreenWidth {
            get {
                return ((int)(this["InfinityScreenWidth"]));
            }
            set {
                this["InfinityScreenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int InfinityScreenHeight {
            get {
                return ((int)(this["InfinityScreenHeight"]));
            }
            set {
                this["InfinityScreenHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentNotation {
            get {
                return ((string)(this["CurrentNotation"]));
            }
            set {
                this["CurrentNotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PlayingTime {
            get {
                return ((int)(this["PlayingTime"]));
            }
            set {
                this["PlayingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentOpeningBookFile {
            get {
                return ((string)(this["CurrentOpeningBookFile"]));
            }
            set {
                this["CurrentOpeningBookFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameNotations {
            get {
                return ((string)(this["GameNotations"]));
            }
            set {
                this["GameNotations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGameFinished {
            get {
                return ((bool)(this["IsGameFinished"]));
            }
            set {
                this["IsGameFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentGameFile {
            get {
                return ((string)(this["CurrentGameFile"]));
            }
            set {
                this["CurrentGameFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGameResignedByA {
            get {
                return ((bool)(this["IsGameResignedByA"]));
            }
            set {
                this["IsGameResignedByA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGameResignedByB {
            get {
                return ((bool)(this["IsGameResignedByB"]));
            }
            set {
                this["IsGameResignedByB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGameDrawnByA {
            get {
                return ((bool)(this["IsGameDrawnByA"]));
            }
            set {
                this["IsGameDrawnByA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGameDrawnByB {
            get {
                return ((bool)(this["IsGameDrawnByB"]));
            }
            set {
                this["IsGameDrawnByB"] = value;
            }
        }
    }
}
