//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinityChess.Offline.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class ThemeSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ThemeSetting defaultInstance = ((ThemeSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ThemeSetting())));
        
        public static ThemeSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 9pt")]
        public global::System.Drawing.Font Font {
            get {
                return ((global::System.Drawing.Font)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 217, 188")]
        public global::System.Drawing.Color BackColorControl {
            get {
                return ((global::System.Drawing.Color)(this["BackColorControl"]));
            }
            set {
                this["BackColorControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color BackColorButton {
            get {
                return ((global::System.Drawing.Color)(this["BackColorButton"]));
            }
            set {
                this["BackColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color BackColorTextbox {
            get {
                return ((global::System.Drawing.Color)(this["BackColorTextbox"]));
            }
            set {
                this["BackColorTextbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color UCDigitalClockColor {
            get {
                return ((global::System.Drawing.Color)(this["UCDigitalClockColor"]));
            }
            set {
                this["UCDigitalClockColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color UCAnalogClockColor {
            get {
                return ((global::System.Drawing.Color)(this["UCAnalogClockColor"]));
            }
            set {
                this["UCAnalogClockColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 133, 181")]
        public global::System.Drawing.Color BackColorForm {
            get {
                return ((global::System.Drawing.Color)(this["BackColorForm"]));
            }
            set {
                this["BackColorForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 133, 181")]
        public global::System.Drawing.Color ChessBoardColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ChessBoardColor1"]));
            }
            set {
                this["ChessBoardColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color ChessBoardColor2 {
            get {
                return ((global::System.Drawing.Color)(this["ChessBoardColor2"]));
            }
            set {
                this["ChessBoardColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColorControl {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorControl"]));
            }
            set {
                this["ForeColorControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ForeColorButton {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorButton"]));
            }
            set {
                this["ForeColorButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ForeColorForm {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorForm"]));
            }
            set {
                this["ForeColorForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ForeColorTextbox {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorTextbox"]));
            }
            set {
                this["ForeColorTextbox"] = value;
            }
        }
    }
}
